{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lakekeeper.fullname" . }}-db
  labels:
    {{- include "lakekeeper.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.database.password | default "" | b64enc | quote }}
{{- end }}
