{{- if not .Values.database.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "philotes-worker.fullname" . }}-db
  labels:
    {{- include "philotes-worker.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.database.password | default "" | b64enc | quote }}
{{- end }}
{{- if not .Values.source.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "philotes-worker.fullname" . }}-source
  labels:
    {{- include "philotes-worker.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.source.password | default "" | b64enc | quote }}
{{- end }}
{{- if not .Values.storage.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "philotes-worker.fullname" . }}-storage
  labels:
    {{- include "philotes-worker.labels" . | nindent 4 }}
type: Opaque
data:
  access-key: {{ .Values.storage.accessKey | default "" | b64enc | quote }}
  secret-key: {{ .Values.storage.secretKey | default "" | b64enc | quote }}
{{- end }}
