{{- if include "philotes-api.createDatabaseSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "philotes-api.fullname" . }}-db
  labels:
    {{- include "philotes-api.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.database.password | b64enc | quote }}
{{- end }}
